export const GROCERY_CATEGORIES = [
  "produce",
  "dairy",
  "meat",
  "seafood",
  "bakery",
  "deli",
  "frozen",
  "canned",
  "dry-goods",
  "snacks",
  "beverages",
  "condiments",
  "spices",
  "breakfast",
  "baby",
  "household",
  "personal-care",
  "pet",
  "other",
] as const;

export type GroceryCategory = (typeof GROCERY_CATEGORIES)[number];

export const CATEGORY_LABELS: Record<GroceryCategory, string> = {
  produce: "Produce",
  dairy: "Dairy & Eggs",
  meat: "Meat & Poultry",
  seafood: "Seafood",
  bakery: "Bakery",
  deli: "Deli",
  frozen: "Frozen",
  canned: "Canned Goods",
  "dry-goods": "Dry Goods & Pasta",
  snacks: "Snacks",
  beverages: "Beverages",
  condiments: "Condiments & Sauces",
  spices: "Spices & Seasonings",
  breakfast: "Breakfast & Cereal",
  baby: "Baby",
  household: "Household",
  "personal-care": "Personal Care",
  pet: "Pet Supplies",
  other: "Other",
};
